### ISSUE TITLE
Location of Helm cache not found

### ISSUE THREAD

**Issue by msche** [sapcc/helm-outdated-dependencies#2]
I was trying to see how the outdated plugin is working an ran in the following situation. On my local machine the env setting for cache is as follows:

```
helm env
...
HELM_REGISTRY_CONFIG="/Users/markschenk/Library/Preferences/helm/registry.json"
HELM_REPOSITORY_CACHE="/Users/markschenk/Library/Caches/helm/repository"
HELM_REPOSITORY_CONFIG="/Users/markschenk/Library/Preferences/helm/repositories.yaml"
```

(working on a mac)

When i try to check whether there are updates I get the following exception:

```
Mark-Schenk:identity-server markschenk$ helm outdated-dependencies list chart/
unable to get an update from the "charts-bitnami-com-bitnami" chart repository (https://charts.bitnami.com/bitnami):
        open /Users/markschenk/.helm/repository/cache/charts-bitnami-com-bitnami-index.yaml: no such file or directory
Error getting latest version of mysql: open /Users/markschenk/.helm/repository/cache/charts-bitnami-com-bitnami-index.yaml: no such file or directory
All charts up to date.
```
Seems that the environment settings are not respected

**Comment by msche** [comment]
Ps: even when I pass the flag `--repository-cache` it's not looking at the correct location

**Comment by msche** [comment]
Reason for failure was that I was using it in combination with Helm version 3 while the plugin is meant for Helm version 2. I cloned the project and upgraded it to Helm V3. The updated helm plugin (renamed it to outdated to distinct it from this one) can be found here: [helm-outdated](https://github.com/UniKnow/helm-outdated)

**Comment by auhlig** [comment]
Cool. So you want to open a PR  @msche?
